apiVersion: apps/v1
kind: Deployment
metadata:
  name: bento
  namespace: bento
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: bento
  template:
    metadata:
      labels:
        app: bento
    spec:
      containers:
        - name: bento
          image: paidjkim/bento:tagname
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/arch: arm64